# Authenticated Primevest API Tests (PowerShell)
# Usage: powershell -ExecutionPolicy Bypass -File test-api-auth.ps1

$baseUrl = "http://localhost:3000"
$token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSkZVekkxTmlJc0ltdHBaQ0k2SWprNU1XTXhZemRpTFRJelpUZ3RORE5pT0MwNE5UTXlMV016WXpjd1pHRTJNamRqTVNJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcGMzTWlPaUpvZEhSd2N6b3ZMMmx1WkdWeGVHUjBlR0p6YUc1aGVHSjBkbk4xTG5OMWNHRmlZWE5sTG1OdkwyRjFkR2d2ZGpFaUxDSnpkV0lpT2lKa056RTBPVFF3TXkwNE5HWmxMVFJqWTJFdFlUWXlNUzB4WlRZeU1qUmtNVE0yT0dJaUxDSmhkV1FpT2lKaGRYUm9aVzUwYVdOaGRHVmtJaXdpWlhod0lqb3hOemN5TlRRMU9UazVMQ0pwWVhRaU9qRTNOekkxTkRJek9Ua3NJbVZ0WVdsc0lqb2lhWE5oYVdGb2MyRnNZbUV5TURJd1FHZHRZV2xzTG1OdmJTSXNJbkJvYjI1bElqb2lJaXdpWVhCd1gyMWxkR0ZrWVhSaElqcDdJbkJ5YjNacFpHVnlJam9pWlcxaGFXd2lMQ0p3Y205MmFXUmxjbk1pT2xzaVpXMWhhV3dpWFgwc0luVnpaWEpmYldWMFlXUmhkR0VpT25zaVpXMWhhV3dpT2lKcGMyRnBZV2h6WVd4aVlUSXdNakJBWjIxaGFXd3VZMjl0SWl3aVpXMWhhV3hmZG1WeWFXWnBaV1FpT25SeWRXVXNJbkJvYjI1bFgzWmxjbWxtYVdWa0lqcG1ZV3h6WlN3aWMzVmlJam9pWkRjeE5EazBNRE10T0RSbVpTMDBZMk5oTFdFMk1qRXRNV1UyTWpJMFpERXpOamhpSW4wc0luSnZiR1VpT2lKaGRYUm9aVzUwYVdOaGRHVmtJaXdpWVdGc0lqb2lZV0ZzTVNJc0ltRnRjaUk2VzNzaWJXVjBhRzlrSWpvaWNHRnpjM2R2Y21RaUxDSjBhVzFsYzNSaGJYQWlPakUzTnpJek1qazVOelo5WFN3aWMyVnpjMmx2Ymw5cFpDSTZJakkyTkRReVl6TTNMV1ppT1RZdE5EY3dZeTFpTkRKbUxUVXdaakJrTnpZNVpHRTNaQ0lzSW1selgyRnViMjU1Ylc5MWN5STZabUZzYzJWOS50R0FHdER0bWZXWDBlSzJzeUZkS2NvNFlaQTc2aWNXLUxIamZKeWZRSUNobERXOHZGTTBqaUZ4bkxGMllGS3RYSXZjNU9DclVuSmdXM251R1B6N1VFQSIsInRva2VuX3R5cGUiOiJiZWFyZXIiLCJleHBpcmVzX2luIjozNjAwLCJleHBpcmVzX2F0IjoxNzcyNTQ1OTk5LCJyZWZyZXNoX3Rva2VuIjoiNXpkbXZkMzNzdGh6IiwidXNlciI6eyJpZCI6ImQ3MTQ5NDAzLTg0ZmUtNGNjYS1hNjIxLTFlNjIyNGQxMzY4YiIsImF1ZCI6ImF1dGhlbnRpY2F0ZWQiLCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImVtYWlsIjoiaXNhaWFoc2FsYmEyMDIwQGdtYWlsLmNvbSIsImVtYWlsX2NvbmZpcm1lZF9hdCI6IjIwMjYtMDItMTFUMTI6MTg6MjQuOTg4NjExWiIsInBob25lIjoiIiwiY29uZmlybWF0aW9uX3NlbnRfYXQiOiIyMDI2LTAyLTExVDEyOjE2OjQ4Ljk3NzU3M1oiLCJjb25maXJtZWRfYXQiOiIyMDI2LTAyLTExVDEyOjE4OjI0Ljk4ODYxMVoiLCJsYXN0X3NpZ25faW5fYXQiOiIyMDI2LTAzLTAzVDEwOjQ0OjM5Ljk0MTIzMVoiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImlzYWlhaHNhbGJhMjAyMEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJkNzE0OTQwMy04NGZlLTRjY2EtYTYyMS0xZTYyMjRkMTM2OGIifSwiaWRlbnRpdGllcyI6W3siaWRlbnRpdHlfaWQiOiJhNjc4OTc5Yi05NjEyLTRmZWEtYjY3MS0wMzA0YTdhNDE1NWYiLCJpZCI6ImQ3MTQ5NDAzLTg0ZmUtNGNjYS1hNjIxLTFlNjIyNGQxMzY4YiIsInVzZXJfaWQiOiJkNzE0OTQwMy04NGZlLTRjY2EtYTYyMS0xZTYyMjRkMTM2OGIiLCJpZGVudGl0eV9kYXRhIjp7ImVtYWlsIjoiaXNhaWFoc2FsYmEyMDIwQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImQ3MTQ5NDAzLTg0ZmUtNGNjYS1hNjIxLTFlNjIyNGQxMzY4YiJ9LCJwcm92aWRlciI6ImVtYWlsIiwibGFzdF9zaWduX2luX2F0IjoiMjAyNi0wMi0xMVQxMjoxNjo0OC45MTk1MjJaIiwiY3JlYXRlZF9hdCI6IjIwMjYtMDItMTFUMTI6MTY6NDguOTE5NTgyWiIsInVwZGF0ZWRfYXQiOiIyMDI2LTAyLTExVDEyOjE2OjQ4LjkxOTU4MloiLCJlbWFpbCI6ImlzYWlhaHNhbGJhMjAyMEBnbWFpbC5jb20ifV0sImNyZWF0ZWRfYXQiOiIyMDI2LTAyLTExVDEyOjE2OjQ4Ljg1NjA4NFoiLCJ1cGRhdGVkX2F0IjoiMjAyNi0wMy0wM1QxMjo1MzoxOS4xODU0NDdaIiwiaXNfYW5vbnltb3VzIjpmYWxzZX19'  # Cookie secret added
$headers = @{ 
  'Accept' = 'application/json'
  'Authorization' = "Bearer $token"
}

# Test authenticated endpoints
'Testing dashboard summary:'
iwr "$baseUrl/api/dashboard/summary" -Method Get -Headers $headers | % StatusCode, @{n='Response';e={($_.Content | ConvertFrom-Json | ConvertTo-Json -Depth 3)} }

'Testing support tickets GET:'
iwr "$baseUrl/api/support/tickets?page=1" -Method Get -Headers $headers | % StatusCode, @{n='Response';e={($_.Content | ConvertFrom-Json | ConvertTo-Json -Depth 3)} }

'Testing support ticket POST:'
$body = @{category='cli';subject='Auth Test';message='Success with token!'} | ConvertTo-Json
iwr "$baseUrl/api/support/tickets" -Method Post -Body $body -ContentType 'application/json' -Headers $headers | % StatusCode, @{n='Response';e={($_.Content | ConvertFrom-Json | ConvertTo-Json -Depth 3)} }

Write-Host '✅ Authenticated tests ready!' -ForegroundColor Green

